name: Build

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install npx
      run: sudo apt-get install upx

    - name: Build
      run: go build -v ./...
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
        go build -ldflags="-w" -o vhstatus-server cmd/main.go

