name: Build

#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Install npx
      run: sudo apt-get install upx

    - name: Build
      run: |
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
        go build -ldflags="-w" -o vhstatus-server cmd/main.go

    - name: Packing executable file
      run: upx vhstatus-server

    - name: Create a release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: ${{ github.ref }}
        body: this release is test-release created by Github Actions.
        draft: true
        prerelease: true

